from easydict import EasyDict as edict

CFG = edict()
CFG.EPOCH = 10000
CFG.DEFAULT_PATH = './save/'
CFG.VGG_MEAN = [103.939, 116.779, 123.68]

CFG.LANENET = edict()
CFG.LANENET.LR = 5e-4
CFG.LANENET.BATCH_SIZE = 8
CFG.LANENET.IMAGE_W = 512
CFG.LANENET.IMAGE_H = 256
CFG.LANENET.DELTA_V = 0.5
CFG.LANENET.DELTA_D = 3.0
CFG.LANENET.PARAM_VAR = 1.0
CFG.LANENET.PARAM_DIST = 1.0
CFG.LANENET.PARAM_REG = 0.01

CFG.HNET = edict()
CFG.HNET.LR = 5e-5
CFG.HNET.BATCH_SIZE = 10
CFG.HNET.IMAGE_H = 128
CFG.HNET.IMAGE_W = 64
